import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { MultiAgentSync } from '../../src/services/multi-agent-sync';
import { GitIgnoreManager } from '../../src/services/gitignore-manager';
import { createTempDir, cleanupTempDir, writeJsonFile } from '../helpers/test-utils';
import fs from 'fs-extra';
import path from 'path';
import type { CraftDeskJson } from '../../src/types/craftdesk-json';
import type { CraftDeskLock } from '../../src/types/craftdesk-lock';

// Mock config manager to read from test directory
vi.mock('../../src/services/config-manager', () => {
  let testConfig: CraftDeskJson | null = null;

  return {
    configManager: {
      getCraftDeskJson: vi.fn(async () => testConfig),
      setTestConfig: (config: CraftDeskJson | null) => {
        testConfig = config;
      },
      getInstallPath: vi.fn(() => '.claude')
    }
  };
});

import { configManager } from '../../src/services/config-manager';

describe('Sync GitIgnore Integration', () => {
  let tempDir: string;
  let sync: MultiAgentSync;
  let gitIgnore: GitIgnoreManager;

  beforeEach(async () => {
    tempDir = await createTempDir('sync-gitignore-test-');
    sync = new MultiAgentSync();
    gitIgnore = new GitIgnoreManager();
    vi.clearAllMocks();
  });

  afterEach(async () => {
    await cleanupTempDir(tempDir);
    (configManager as any).setTestConfig(null);
  });

  describe('syncCraft creates .gitignore in target directories', () => {
    it('should create .gitignore in all target directories after sync', async () => {
      // Setup multi-agent config
      const config: CraftDeskJson = {
        name: 'test-project',
        version: '1.0.0',
        multiAgent: {
          enabled: true,
          canonical: '.claude',
          targets: ['.claude/skills', '.agents/skills', '.cursor/skills'],
          autoSync: true
        }
      };

      await writeJsonFile(path.join(tempDir, 'craftdesk.json'), config);
      (configManager as any).setTestConfig(config);

      // Create lockfile with a managed skill
      const lock: CraftDeskLock = {
        version: '0.5.0',
        crafts: {
          'ruby-expert': {
            name: 'ruby-expert',
            version: '1.0.0',
            type: 'skill',
            resolved: 'https://example.com/ruby-expert-1.0.0.tgz',
            integrity: 'sha512-abc123'
          }
        },
        pluginTree: {}
      };
      await writeJsonFile(path.join(tempDir, 'craftdesk.lock'), lock);

      // Create source skill
      const skillDir = path.join(tempDir, 'temp-skill');
      await fs.ensureDir(skillDir);
      await fs.writeFile(
        path.join(skillDir, 'SKILL.md'),
        '# Ruby Expert\n\nExpert knowledge about Ruby.'
      );

      // Sync to all targets
      const result = await sync.syncCraft('ruby-expert', skillDir, tempDir);

      expect(result.synced.length).toBeGreaterThan(0);
      expect(result.failed).toHaveLength(0);

      // Assert: .gitignore exists in target directories
      const agentsGitignore = path.join(tempDir, '.agents/skills/.gitignore');
      const cursorGitignore = path.join(tempDir, '.cursor/skills/.gitignore');

      expect(await fs.pathExists(agentsGitignore)).toBe(true);
      expect(await fs.pathExists(cursorGitignore)).toBe(true);

      // Assert: .gitignore contains the managed skill
      const agentsContent = await fs.readFile(agentsGitignore, 'utf-8');
      const cursorContent = await fs.readFile(cursorGitignore, 'utf-8');

      expect(agentsContent).toContain('ruby-expert/');
      expect(agentsContent).toContain('# Auto-generated by CraftDesk');
      expect(cursorContent).toContain('ruby-expert/');
      expect(cursorContent).toContain('# Auto-generated by CraftDesk');
    });

    it('should include embedded skills as NOT ignored in target .gitignore', async () => {
      const config: CraftDeskJson = {
        name: 'test-project',
        version: '1.0.0',
        embedded: ['my-local-skill'],
        multiAgent: {
          enabled: true,
          canonical: '.claude',
          targets: ['.claude/skills', '.cursor/skills'],
          autoSync: true
        }
      };

      await writeJsonFile(path.join(tempDir, 'craftdesk.json'), config);
      (configManager as any).setTestConfig(config);

      // Create lockfile with a managed skill
      const lock: CraftDeskLock = {
        version: '0.5.0',
        crafts: {
          'managed-skill': {
            name: 'managed-skill',
            version: '1.0.0',
            type: 'skill',
            resolved: 'https://example.com/managed-skill-1.0.0.tgz',
            integrity: 'sha512-abc123'
          }
        },
        pluginTree: {}
      };
      await writeJsonFile(path.join(tempDir, 'craftdesk.lock'), lock);

      // Create and sync a skill
      const skillDir = path.join(tempDir, 'temp-skill');
      await fs.ensureDir(skillDir);
      await fs.writeFile(path.join(skillDir, 'SKILL.md'), '# Managed Skill');

      await sync.syncCraft('managed-skill', skillDir, tempDir);

      // Check target .gitignore
      const cursorGitignore = path.join(tempDir, '.cursor/skills/.gitignore');
      expect(await fs.pathExists(cursorGitignore)).toBe(true);

      const content = await fs.readFile(cursorGitignore, 'utf-8');
      expect(content).toContain('managed-skill/');
      expect(content).toContain('# NOT ignored: my-local-skill/');
    });

    it('should not create target .gitignore when multi-agent is disabled', async () => {
      const config: CraftDeskJson = {
        name: 'test-project',
        version: '1.0.0',
        multiAgent: {
          enabled: false,
          canonical: '.claude',
          targets: ['.claude/skills', '.cursor/skills']
        }
      };

      await writeJsonFile(path.join(tempDir, 'craftdesk.json'), config);
      (configManager as any).setTestConfig(config);

      // autoUpdateTargets should be a no-op
      await gitIgnore.autoUpdateTargets(tempDir);

      const cursorGitignore = path.join(tempDir, '.cursor/skills/.gitignore');
      expect(await fs.pathExists(cursorGitignore)).toBe(false);
    });
  });

  describe('syncAllCrafts creates .gitignore in target directories', () => {
    it('should create .gitignore in targets after syncing all crafts', async () => {
      const config: CraftDeskJson = {
        name: 'test-project',
        version: '1.0.0',
        multiAgent: {
          enabled: true,
          canonical: '.claude',
          targets: ['.claude/skills', '.windsurf/skills'],
          autoSync: true
        }
      };

      await writeJsonFile(path.join(tempDir, 'craftdesk.json'), config);
      (configManager as any).setTestConfig(config);

      // Create lockfile
      const lock: CraftDeskLock = {
        version: '0.5.0',
        crafts: {
          'skill-a': {
            name: 'skill-a',
            version: '1.0.0',
            type: 'skill',
            resolved: 'https://example.com/a.tgz',
            integrity: 'sha512-a'
          },
          'skill-b': {
            name: 'skill-b',
            version: '2.0.0',
            type: 'skill',
            resolved: 'https://example.com/b.tgz',
            integrity: 'sha512-b'
          }
        },
        pluginTree: {}
      };
      await writeJsonFile(path.join(tempDir, 'craftdesk.lock'), lock);

      // Create skills in canonical location
      for (const name of ['skill-a', 'skill-b']) {
        const skillPath = path.join(tempDir, '.claude/skills', name);
        await fs.ensureDir(skillPath);
        await fs.writeFile(path.join(skillPath, 'SKILL.md'), `# ${name}`);
      }

      // Sync all crafts
      const results = await sync.syncAllCrafts(tempDir);

      expect(results).toHaveLength(2);
      expect(results.every(r => r.failed.length === 0)).toBe(true);

      // Assert: .gitignore in windsurf target
      const windsurfGitignore = path.join(tempDir, '.windsurf/skills/.gitignore');
      expect(await fs.pathExists(windsurfGitignore)).toBe(true);

      const content = await fs.readFile(windsurfGitignore, 'utf-8');
      expect(content).toContain('skill-a/');
      expect(content).toContain('skill-b/');
    });
  });

  describe('autoUpdateTargets', () => {
    it('should skip canonical directory', async () => {
      const config: CraftDeskJson = {
        name: 'test-project',
        version: '1.0.0',
        multiAgent: {
          enabled: true,
          canonical: '.claude',
          targets: ['.claude/skills', '.cursor/skills']
        }
      };

      await writeJsonFile(path.join(tempDir, 'craftdesk.json'), config);
      (configManager as any).setTestConfig(config);

      // Create lockfile
      const lock: CraftDeskLock = {
        version: '0.5.0',
        crafts: {
          'test-skill': {
            name: 'test-skill',
            version: '1.0.0',
            type: 'skill',
            resolved: 'https://example.com/test.tgz',
            integrity: 'sha512-test'
          }
        },
        pluginTree: {}
      };
      await writeJsonFile(path.join(tempDir, 'craftdesk.lock'), lock);

      await gitIgnore.autoUpdateTargets(tempDir);

      // .cursor/skills/.gitignore should be created
      const cursorGitignore = path.join(tempDir, '.cursor/skills/.gitignore');
      expect(await fs.pathExists(cursorGitignore)).toBe(true);

      // .claude/skills/.gitignore should NOT be created by autoUpdateTargets
      // (it's handled by autoUpdate instead)
      const claudeGitignore = path.join(tempDir, '.claude/skills/.gitignore');
      expect(await fs.pathExists(claudeGitignore)).toBe(false);
    });

    it('should be a no-op when no multiAgent config exists', async () => {
      const config: CraftDeskJson = {
        name: 'test-project',
        version: '1.0.0'
      };

      await writeJsonFile(path.join(tempDir, 'craftdesk.json'), config);
      (configManager as any).setTestConfig(config);

      // Should not throw
      await expect(gitIgnore.autoUpdateTargets(tempDir)).resolves.not.toThrow();
    });
  });
});
